<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_PageHeader</name>
   <tag></tag>
   <elementGuidId>eb79e128-cc43-416b-b76c-f34f04db78c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainMenu']/ul//li[.//b[text()='${PageLabel}']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']/ul//li[.//b[text()='${PageLabel}']]</value>
   </webElementProperties>
</WebElementEntity>
